_wandb:
    value:
        cli_version: 0.27.0
        e:
            r15cz122wspyxo7gn4wwgsxyb11jeut3:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    macModel: Mac14,7
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "9663676416"
                codePath: src/pathmnist_mlops/train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "216562745344"
                email: Schreiner.Simon@campus.lmu.de
                executable: /Users/simons/anaconda3/envs/mlops2/bin/python
                git:
                    commit: b04cc2d31621aef67886b56aa3e61699d3738a02
                    remote: https://syyymonn:@github.com/pamudinj/MLOps_Project_LSP.git
                host: Simons-MacBook-Pro.local
                memory:
                    total: "8589934592"
                os: macOS-15.3-arm64-arm-64bit
                program: /Users/simons/Library/Mobile Documents/com~apple~CloudDocs/MLOps_Project_LSP/src/pathmnist_mlops/train.py
                python: CPython 3.12.13
                root: .
                startedAt: "2026-05-31T09:45:39.433894Z"
                writerId: r15cz122wspyxo7gn4wwgsxyb11jeut3
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "3":
                - 7
                - 66
            "4": 3.12.13
            "5": 0.27.0
            "12": 0.27.0
            "13": darwin-arm64
lr:
    value: 0.001
