steps:

  - name: "gcr.io/cloud-builders/docker"

    args:
      [
        "build",

        "-f",
        "dockerfiles/drift_api.dockerfile",

        "-t",
        "europe-west1-docker.pkg.dev/mlops-project-497719/mlops-container-registry/pathmnist-drift-api:latest",

        ".",
      ]

images:

  - "europe-west1-docker.pkg.dev/mlops-project-497719/mlops-container-registry/pathmnist-drift-api:latest"