project: pathmnist-mlops

command:
  - python
  - -m
  - pathmnist_mlops.train
  - ${args_no_hyphens}

method: random

metric:
  goal: maximize
  name: val_acc

parameters:

  training.learning_rate:
    values: [0.0001, 0.001]

  training.batch_size:
    values: [32, 64]

  training.epochs:
    values: [10, 20]

run_cap: 2