name: Build Training Container

on:

  push:
    branches:
      - main

    paths:
      - "dockerfiles/train.dockerfile"
      - "cloudbuild_train.yaml"
      - ".github/workflows/build_train.yaml"
      - "src/pathmnist_mlops/train.py"


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v7

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json:
            ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Submit cloud build
        run: |
          gcloud builds submit \
            . \
            --config \
            cloudbuild_train.yaml \
            --async
