name: Unit Tests & Build Container

on:

  push:
    branches:
      - main

    paths:
      - "dockerfiles/train.dockerfile"
      - "cloudbuild_containers.yaml"
      - ".github/workflows/build_container.yaml"


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json:
            ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Submit cloud build
        run: |
          gcloud builds submit \
            . \
            --config \
            cloudbuild_containers.yaml \
            --async
